---
- name: Install Apache httpd servier with an openssl ca and certificated
  hosts: all
  become: yes
  vars:
    - is_openssl_template: True
    - fqn_website: test.parisjug.net
  roles:
    - common
    - openssl-setup-ca
    - openssl-create-site-certficat